spring:
  application:
    name: springBot
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changeLog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
    generate-ddl: false
    show-sql: true

tg:
  bot:
    token: 5460835709:AAFzVvUkO7RVxQPsAvH3WG97LrdRe2KuA78
    name: yontarebot
    chat-id: 598118024
#    chat-id: -1001618397810